name = "sim-cleaning"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "sim-db"
database_id = "b5e982ef-fd13-4023-a767-a313ad748fa6"

[vars]
NEXT_PUBLIC_SITE_NAME = "SparkleServ"
